# Generated by Django 5.0.6 on 2024-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("dob", models.DateField()),
                ("branch", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=15)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "Human Resources"),
                            ("IT", "Information Technology"),
                            ("FIN", "Finance"),
                            ("MKT", "Marketing"),
                            ("SALES", "Sales"),
                            ("OPS", "Operations"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
